name: "Terraform main apply"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Main apply"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform format
        run: terraform fmt -check

      - name: Terraform init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.TERRAFORM_SERVICE_ACCOUNT }}

      - name: Terraform validate
        run: terraform validate -no-color

      - name: Terraform plan
        id: tfplan
        run: terraform plan -no-color -out tfplan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.TERRAFORM_SERVICE_ACCOUNT }}

      - name: Terraform apply
        run: terraform apply -no-color -auto-approve tfplan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.TERRAFORM_SERVICE_ACCOUNT }}
