name: "Terraform PR plan"

on:
  pull_request:

jobs:
  terraform-plan:
    name: "Plan"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform format
        run: terraform fmt -check

      - name: Terraform init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.TERRAFORM_SERVICE_ACCOUNT }}

      - name: Terraform validate
        run: terraform validate -no-color

      - name: Terraform plan
        id: tfplan
        run: terraform plan -no-color
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.TERRAFORM_SERVICE_ACCOUNT }}

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: plan
          recreate: true
          message: |
            ## Plan 📝
            ```bash
            ${{ steps.tfplan.outputs.stdout }}
            ```
